name: Bump Tag
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: bump tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.37.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch
          DRY_RUN: true
          RELEASE_BRANCHES: main
      # todo: remove suffix when package is stable
      - name: update tag with suffix
        run: |
          git tag ${{ steps.tag_version.outputs.new_tag }}-preview
          git push origin ${{ steps.tag_version.outputs.new_tag }}-preview
