name: Bump Tag
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: get latest tag
        id: latest_tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0)
          echo "::set-output name=tag::$latest_tag"
      - name: bump tag
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const currentTag = '${{ steps.latest_tag.outputs.tag }}';
            const [version, suffix] = currentTag.split('-');
            const [major, minor, patch] = version.split('.').map(Number);
            const newTag = `${major}.${minor}.${patch + 1}-${suffix || 'preview'}`;
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${newTag}`,
              sha: context.sha
            });
            console.log(`new tag created: ${newTag}`);
